############################
## CHANGE THESE
############################

baseURL: 'https://Ipad-pc.github.io/Linkr'
title: Linkr

############################
## MODULES
############################

module:
  imports:
    - path: github.com/chrede88/L1nkr


############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


